public class Project2 {
 public static void main(String[] args) {
   
        System.out.println("L       EEEE    OOOO    L       Y  Y    L   ");
        System.out.println("L       E       O  O    L        YY     L   ");
        System.out.println("L       E       O  O    L         Y     L   ");
        System.out.println("L       EEEE    O  O    L         Y     L   ");
        System.out.println("L       E       O  O    L         Y     L   ");
        System.out.println("LLLL    EEEE    OOOO    LLLL      Y     LLLL");
    }
}
    
